@ATON_Test_Ploblem_HostAddress = http://localhost:5106

POST https://localhost:7108/api/User
Content-Type: application/json
Accept: application/json

{
    "login": "Diana201",
    "password": "di",
    "name": "Dishka",
    "gender": 0,
    "admin": true,
    "birthday": "2004-10-18"
}
###
