@ATON_Test_Ploblem_HostAddress = http://localhost:5106

POST https://localhost:7108/api/User
Content-Type: application/json
Accept: application/json
//создать нового админа
{
    "login": "Diana201",
    "password": "di",
    "name": "Dishka",
    "gender": 0,
    "admin": true,
    "birthday": "2004-10-18"
}
###

PUT https://localhost:7108/api/User/11111111-2222-3333-4444-555555555555
Content-Type: application/json
Accept: application/json
//изменить данные пользователя
{
    "name": "DianaSlanova",
    "gender": 0,
    "birthday": "2003-07-27"
}
###

Get https://localhost:7108/api/User/11111111-2222-3333-4444-555555555555
Accept: application/json
//вывести данные пользователя по id
###

PUT https://localhost:7108/api/User/11111111-2222-3333-4444-555555555555/password
Content-Type: application/json
Accept: application/json
//изменить пароль
{
  "password": "DianaLALALA"
}
###

PUT https://localhost:7108/api/User/11111111-2222-3333-4444-555555555555/login
Content-Type: application/json
Accept: application/json
//изменить логин
{
  "login": "DianaNewLogin"
}
###

GET https://localhost:7108/api/User/getAll
Accept: application/json
//посмотреть всех активных пользователей
###

GET https://localhost:7108/api/User/Admin/getByLogin
Accept: application/json
//получить пользователя по логину

###

GET https://localhost:7108/api/User/Admin/password/singIn
Accept: application/json
//получить пользователя по логину и паролю

###
